spring.application.name=progetto-siw-tornei

spring.datasource.url=jdbc:postgresql://localhost:5432/gestione_tornei
spring.datasource.username=postgres
spring.datasource.password=Piramide_333

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true